### PR TITLE
Detect PCAP write errors

### PR DESCRIPTION
**Pull request by pspacek**

### CODE REVIEW

**Comment by pspacek** [comment]
Essentially this is workaround for libpcap API deficiency:
See https://github.com/the-tcpdump-group/libpcap/issues/87

Given that libpcap has this problem for at least 14 years, and that I could not find any better API, I think this is best we can do.

Performance sensitive part is in separate commit to make review easier. In my tests it was not significantly slowing down _real_ workloads. Additional option could be switch in output constructor so the check could be disabled when creating object, but I'm not sure if it is worth.

**Comment by jelu** [comment]
Disturbing find, it might take me some time to dig into this.

Another way to "solve" this would be to create a `fpcap` output where status from `fwrite()` can be checked, the PCAP format is quite simple (look at `input/fpcap` for example). Doing that might be a performance boost compared to libpcap without this.

**Comment by pspacek** [comment]
Yes, `fpcap` writer is also an option. I just wanted quick fix and do not have time to mess with PCAP header magics, it is a mess.

**Comment by jelu** [comment]
I'm rejecting this because it's not really helpful to just die on error without any option or way to handle errors.

I've added `output.pcap:have_errors()` in #196 that can be use where-ever to detect write errors.

**Pull request closed without merging**
