### PR TITLE
getopt: detect incorrect short strings

### PR DESCRIPTION
**Pull request by pspacek**

### CODE REVIEW

**Comment by jelu** [comment]
#build

**Comment by jelu** [comment]
@pspacek Why are you calling this "nil fix" ? `short` is suppose to be able to be nil.

**Comment by pspacek** [comment]
Do you mean branch name? Well, I did not want to have branch name `getopt_short_must_be_nil_or_string_of_length_one` :stuck_out_tongue:

**Comment by pspacek** [comment]
> remove text about nil since the check checks that it's not nil
That was meant as hint for user who made mistake. If someone used short `""` it would let him/her know straight away that `nil` is better option. (This happened in DNS Shotgun, that's why I thought it would be useful.) Anyway, it is so minor nit that we do not need to waste time on it.

**Comment by jelu** [comment]
> That was meant as hint for user who made mistake.

Well, error messages is not a good place for documentation.

**Comment by jelu** [comment]
> Do you mean branch name?

Yes, it kinda indicated that something else was wrong also. Btw, I don't really care about branch names so you can shorten them as much as you want.

**Pull request merged**
