### PR TITLE
output.tlscli

### PR DESCRIPTION
**Pull request by tomaskrizek**
basic TLS client with no certificate validation.

### CODE REVIEW

**Comment by tomaskrizek** [comment]
Updated with the latest working version.

The TLS client is basically the TCP client, with removed unused non-blocking mode (#101) and added TLS session.

I've also had to remove the `poll()` function and timeout handling. I'm not sure how to properly implement it with gnutls.

**Comment by jelu** [comment]
#build

**Comment by jelu** [comment]
@tomaskrizek Please test my changes.

**Comment by tomaskrizek** [comment]
Thanks for the changes! The only issue I see is when the response times out - lua receives `nil` instead of 0-length packet.

**Comment by jelu** [comment]
@tomaskrizek Are you sure? It should only return 0 if there is an error, I can't see where it would return 0 on timeout.

**Comment by tomaskrizek** [comment]
`GNUTLS_E_TIMEDOUT` has to be handled when calling `gnutls_record_recv()`.

Looking at e4ddbf19d62ce222d17c5b7e39bcbaea1f57bb64, I think the right action to do when we get `GNUTLS_E_AGAIN` or `GNUTLS_E_INTERRUPTED` is to call the function again. Or is there some reason to return a 0-length packet in these cases?

**Comment by jelu** [comment]
I can't find in the docs that `gnutls_record_recv()` returns `GNUTLS_E_TIMEDOUT`.

I can only find that it is used for the DTLS features.

Have you tested this?

**Comment by tomaskrizek** [comment]
Yes, I can verify this with GnuTLS 3.6.4. `gnutls_record_recv()` returns `GNUTLS_E_TIMEDOUT` in case the timeout configured with `gnutls_record_set_timeout()` is reached.

**Comment by tomaskrizek** [comment]
@jelu Seems to work fine now, thanks!

**Pull request merged**
