### PR TITLE
Ability to read PCAP from stdin

### PR DESCRIPTION
**Pull request by pspacek**
(and a related fix in lib.getopt)

### CODE REVIEW

**Review by jelu — CHANGES_REQUESTED** [review]
`input_fpcap_destroy()` will now close stdin.

**Comment by pspacek** [comment]
> `input_fpcap_destroy()` will now close stdin.

What variant do you prefer? Making `input_fpcap_destroy()` noop if input is stdin?

**Comment by pspacek** [comment]
> I don't have time right now to look at the `getopt` changes, so if you want the stdin stuff merged sooner then split that into a separate PR.

The other commits are not useful for me without the getopt fix so there is no point in splitting it. If you find two minutes for it you will find out that the diff just moves `if need_arg then` to the very beginning, or in other words, `-` special case now kicks in _only if we are not already expecting an argument_. Formerly `-` was special-cased even when expecting an argument which effectively prevented `-` from being used.

**Comment by jelu** [comment]
@pspacek I can read the diff, but I am unsure it works all the time. For example `-r --`.

**Comment by jelu** [comment]
> Making input_fpcap_destroy() noop if input is stdin?

Yes.

**Comment by pspacek** [comment]
> @pspacek I can read the diff, but I am unsure it works all the time. For example `-r --`.

If "works" == "does the same thing as GNU getopt" then I believe the answer is "yes".

GNU Getopt behavior:
```
$ seq --version
seq (GNU coreutils) 8.32
$ seq -f -- 1 2
seq: format ‘--’ has no % directive
$ seq --format -- 1 2
seq: format ‘--’ has no % directive
```
In other words, `--` does not have special meaning if it is present at position where an argument is expected.

**Comment by pspacek** [comment]
> > Making input_fpcap_destroy() noop if input is stdin?
> 
> Yes.

It's not exactly noop after all so I let 8ff81a0 as separate fixup commit for review. I can squash that if you like it.

**Pull request merged**
