### PR TITLE
input/pcap: cleanup after failure to open PCAP

### PR DESCRIPTION
**Pull request by tomaskrizek**
Ensure the behaviour when reading PCAP header fails is consistent with
trying to open a non-existent file.

Attempting to call run() after any error during opening now leads to a
fatal error (no PCAP opened). This can happen if the input file exists,
but isn't a PCAP.

### CODE REVIEW

**Comment by jelu** [comment]
No, `fpcap`/`mmpcap` are not meant to be reusable on failure.

**Comment by jelu** [comment]
> Attempting to call run() after any error during opening now leads to a
fatal error (no PCAP opened).

You should not call `run()` if open failed.

**Comment by tomaskrizek** [comment]
> > Attempting to call run() after any error during opening now leads to a
> > fatal error (no PCAP opened).
> 
> You should not call `run()` if open failed.

Well, that really isn't clear, as none of the [examples](https://github.com/DNS-OARC/dnsjit/tree/develop/examples) nor the [man page](https://github.com/DNS-OARC/dnsjit/blob/develop/src/input/fpcap.lua#L20) (or the documentation for `run()`) mention it or check the return code.

It can be quite confusing:
- you open() a non-existing file and call run() -> you get a critical and a fatal error and it exits
- you open() an existing file, but not a PCAP and call run() -> you get a critical error, but runtime continues in undefined state

**Comment by jelu** [comment]
I agree that documentation could be better, especially when it comes to the mindset you should have when using dnsjit.

dnsjit is meant for testing, research and experimenting, where speed is more important then stability.

**Pull request closed without merging**
